# Checking and describing the generated data

It is always beneficial to add a notebook that quickly looks into the data to
help you remember, which data you collected and if it actually looks correct.

In [2]:
from algbench import describe, read_as_pandas, Benchmark
from _conf import EXPERIMENT_DATA
from _utils import ResultKey

In [3]:
describe(EXPERIMENT_DATA)

An entry in the database can look like this:
_____________________________________________
 result:
| rq: rq2_k_scaling
| n: 100000
| dim: 3
| k: 256
| kind: blobs
| asw: 0.08276387622619279
 timestamp: 2026-05-05T02:19:55.978156
 runtime: 2.38315486907959
 stdout: []
 stderr: []
 logging: []
 env_fingerprint: 151c08c02bb571b066dce61eb3fe7ad60d16f319
 args_fingerprint: e7dd9856a6e6fbc90382e6fbb59a66aa483f0051
 parameters:
| func: compute_silhouette
| args:
|| instance_name: rq=rq2_k_scaling__dim=3__n=100000__k=256__kind=blobs__seed=200885147366164228...
|| strategy: fast_auto_score
 argv: ['/ibr/home/hoang/bachelorarbeit-an-hoang/.venv/lib/python3.14/site-packages/...
 env:
| hostname: algra01
| python_version: 3.14.3 (main, Mar  3 2026, 14:59:53) [Clang 21.1.4 ]
| python: /ibr/home/hoang/bachelorarbeit-an-hoang/.venv/bin/python3
| cwd: /ibr/home/hoang/bachelorarbeit-an-hoang/evaluation/research_questions/2026-05...
| git_revision: c9c183d357ab609830e27748d55d896ba4962eb7
| python_file: /ibr/home/hoang/bachelorarbeit-an-hoang/.venv/lib/python3.14/site-packages/sl...
______________________________________________
Note that this is only based on the first entry, other entries could differ.

In [ ]:
t = read_as_pandas(
    EXPERIMENT_DATA,
    lambda entry: (
        {
            "instance_name": entry["parameters"]["args"]["instance_name"],
            ResultKey.N_POINTS: entry["result"][ResultKey.NUM_POINTS],
            ResultKey.N_CLUSTERS: entry["result"][ResultKey.NUM_CLUSTERS],
            ResultKey.N_DIMENSIONS: entry["result"][ResultKey.NUM_DIMENSIONS],
            "time_limit": entry["parameters"]["args"]["time_limit"],
            "runtime": entry["runtime"],  # automatically saved
            "strategy": entry["parameters"]["args"]["strategy"],
            "opt_tol": entry["parameters"]["args"]["opt_tol"],
            ResultKey.OBJECTIVE: entry["result"][ResultKey.OBJECTIVE],
            ResultKey.UPPER_BOUND: entry["result"][ResultKey.UPPER_BOUND],
            ResultKey.STATUS: entry["result"][ResultKey.STATUS],
            # "silhouette_samples": entry["result"]["silhouette_samples"].tolist(),
            # "cluster_labels": entry["result"]["cluster_labels"].tolist(),
        }
    ),
)
t.drop_duplicates(subset=["instance_name", "strategy", "opt_tol"], inplace=True)
t["opt_gap"] = (
    abs(t[ResultKey.OBJECTIVE] - t[ResultKey.UPPER_BOUND]) / t[ResultKey.UPPER_BOUND]
)
t.sort_values(
    [
        ResultKey.NUM_POINTS,
        ResultKey.NUM_CLUSTERS,
        ResultKey.NUM_DIMENSIONS,
        "instance_name",
    ]
)

,instance_name,num_points,num_clusters,num_dimensions,time_limit,runtime,strategy,opt_tol,objective,upper_bound,opt_gap
132,blob_N5_K2_D1_seed0,5,2,1,90,0.029111,GurobiSilhouetteSolver,0.001,0.555518,0.555518,0.000000e+00
133,blob_N5_K2_D1_seed0,5,2,1,90,0.028769,GurobiSilhouetteSolver,0.010,0.555518,0.555518,0.000000e+00
134,blob_N5_K2_D1_seed0,5,2,1,90,0.028853,GurobiSilhouetteSolver,0.100,0.555518,0.555518,0.000000e+00
135,blob_N5_K2_D1_seed0,5,2,1,90,0.030534,GurobiSilhouetteSolver,0.250,0.555518,0.555518,0.000000e+00
20,blob_N5_K2_D1_seed1,5,2,1,90,0.041987,GurobiSilhouetteSolver,0.001,0.563161,0.563592,7.662595e-04
...,...,...,...,...,...,...,...,...,...,...,...
127,blob_N11_K4_D3_seed1,11,4,3,90,0.248271,GurobiSilhouetteSolver,0.250,0.767143,0.958679,1.997918e-01
160,blob_N11_K4_D3_seed2,11,4,3,90,6.883508,GurobiSilhouetteSolver,0.001,0.640213,0.640213,1.734147e-16
161,blob_N11_K4_D3_seed2,11,4,3,90,6.945091,GurobiSilhouetteSolver,0.010,0.640213,0.640213,1.734147e-16
162,blob_N11_K4_D3_seed2,11,4,3,90,6.770830,GurobiSilhouetteSolver,0.100,0.640213,0.698439,8.336623e-02
163,blob_N11_K4_D3_seed2,11,4,3,90,4.482894,GurobiSilhouetteSolver,0.250,0.640213,0.799321,1.990545e-01

In [13]:
for entry in Benchmark(EXPERIMENT_DATA):
    if (
        entry["parameters"]["args"]["instance_name"] == "blob_N10_K2_D1_seed1"
        and entry["parameters"]["args"]["strategy"] == "GurobiSilhouetteSolver"
    ):
        print("=====================================")
        stdout = "".join(e[1] for e in entry["stdout"])
        stderr = "".join(e[1] for e in entry["stderr"])
        print(stdout)
        print(stderr)
        if not stdout.strip():
            print("No stdout")
        print("=====================================")

=====================================
Set parameter LogToConsole to value 1
Set parameter TimeLimit to value 90
Set parameter MIPGap to value 0.001
Set parameter NonConvex to value 2
Gurobi Optimizer version 13.0.1 build v13.0.1rc0 (linux64 - "Ubuntu 24.04.4 LTS")

CPU model: AMD Ryzen 9 7900 12-Core Processor, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 12 physical cores, 24 logical processors, using up to 24 threads

Non-default parameters:
TimeLimit  90
MIPGap  0.001
NonConvex  2

Optimize a model with 21 rows, 102 columns and 94 nonzeros (Max)
Model fingerprint: 0x1227911a
Model has 10 linear objective coefficients
Model has 30 quadratic constraints
Model has 114 simple general constraints
  10 MAX, 20 AND, 84 INDICATOR
Variable types: 60 continuous, 42 integer (42 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [5e-01, 1e+01]
  Objective range  [1e-01, 1e-01]
  Bounds range     [1e+00, 1e+01]
  RHS range        [1e+00, 1e+00]
  GenCon rhs range [1e+00, 2e+00]
  GenCon coe range [1e+00, 1e+00]

Using branch priorities.
User MIP start produced solution with objective 0.628188 (0.00s)
User MIP start produced solution with objective 0.658185 (0.00s)
User MIP start produced solution with objective 0.672517 (0.01s)
User MIP start produced solution with objective 0.678559 (0.01s)
User MIP start produced solution with objective 0.680407 (0.01s)
Loaded user MIP start with objective 0.680407

Presolve added 136 rows and 17 columns
Presolve time: 0.00s
Presolved: 703 rows, 282 columns, 2034 nonzeros
Presolved model has 10 bilinear constraint(s)

Solving non-convex MIQCP to global optimality

Variable types: 242 continuous, 40 integer (39 binary)

Root relaxation: objective 9.830796e-01, 293 iterations, 0.00 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    0.98308    0   11    0.68041    0.98308  44.5%     -    0s
     0     0    0.96732    0   20    0.68041    0.96732  42.2%     -    0s
     0     0    0.96538    0   20    0.68041    0.96538  41.9%     -    0s
     0     0    0.96441    0   20    0.68041    0.96441  41.7%     -    0s
     0     0    0.95699    0   20    0.68041    0.95699  40.7%     -    0s
     0     0    0.93721    0   20    0.68041    0.93721  37.7%     -    0s
     0     0    0.93200    0   20    0.68041    0.93200  37.0%     -    0s
     0     0    0.91344    0   20    0.68041    0.91344  34.2%     -    0s
     0     0    0.91157    0   20    0.68041    0.91157  34.0%     -    0s
     0     0    0.91066    0   20    0.68041    0.91066  33.8%     -    0s
     0     0    0.90565    0   20    0.68041    0.90565  33.1%     -    0s
     0     0    0.87212    0   18    0.68041    0.87212  28.2%     -    0s
     0     0    0.87018    0   18    0.68041    0.87018  27.9%     -    0s
     0     0    0.85548    0   18    0.68041    0.85548  25.7%     -    0s
     0     0    0.84571    0   18    0.68041    0.84571  24.3%     -    0s
     0     0    0.84136    0   19    0.68041    0.84136  23.7%     -    0s
     0     0    0.82573    0   18    0.68041    0.82573  21.4%     -    0s
     0     0    0.81849    0   17    0.68041    0.81849  20.3%     -    0s
     0     0    0.81785    0   17    0.68041    0.81785  20.2%     -    0s
     0     0    0.81439    0   17    0.68041    0.81439  19.7%     -    0s
     0     0    0.81419    0   16    0.68041    0.81419  19.7%     -    0s
     0     0    0.80723    0   17    0.68041    0.80723  18.6%     -    0s
     0     0    0.80723    0   17    0.68041    0.80723  18.6%     -    0s
     0     0    0.79655    0   17    0.68041    0.79655  17.1%     -    0s
     0     0    0.78659    0   19    0.68041    0.78659  15.6%     -    0s
     0     0    0.78659    0   19    0.68041    0.78659  15.6%     -    0s
     0     2    0.78659    0   19    0.68041    0.78659  15.6%     -    0s

Cutting planes:
  Gomory: 5
  MIR: 52
  Flow cover: 95
  RLT: 42
  Relax-and-lift: 6
  BQP: 61

Explored 2564 nodes (14148 simplex iterations) in 0.31 seconds (0.44 work units)
Thread count was 24 (of 24 available processors)

Solution count 5: 0.680407 0.678559 0.672517 ... 0.628188

Optimal solution found (tolerance 1.00e-03)
Best objective 6.804072772339e-01, best bound 6.808893477045e-01, gap 0.0709%


=====================================
=====================================
Set parameter LogToConsole to value 1
Set parameter TimeLimit to value 90
Set parameter MIPGap to value 0.01
Set parameter NonConvex to value 2
Gurobi Optimizer version 13.0.1 build v13.0.1rc0 (linux64 - "Ubuntu 24.04.4 LTS")

CPU model: AMD Ryzen 9 7900 12-Core Processor, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 12 physical cores, 24 logical processors, using up to 24 threads

Non-default parameters:
TimeLimit  90
MIPGap  0.01
NonConvex  2

Optimize a model with 21 rows, 102 columns and 94 nonzeros (Max)
Model fingerprint: 0x1227911a
Model has 10 linear objective coefficients
Model has 30 quadratic constraints
Model has 114 simple general constraints
  10 MAX, 20 AND, 84 INDICATOR
Variable types: 60 continuous, 42 integer (42 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [5e-01, 1e+01]
  Objective range  [1e-01, 1e-01]
  Bounds range     [1e+00, 1e+01]
  RHS range        [1e+00, 1e+00]
  GenCon rhs range [1e+00, 2e+00]
  GenCon coe range [1e+00, 1e+00]

Using branch priorities.
User MIP start produced solution with objective 0.628188 (0.00s)
User MIP start produced solution with objective 0.658185 (0.00s)
User MIP start produced solution with objective 0.672517 (0.00s)
User MIP start produced solution with objective 0.678559 (0.01s)
User MIP start produced solution with objective 0.680407 (0.01s)
Loaded user MIP start with objective 0.680407

Presolve added 136 rows and 17 columns
Presolve time: 0.00s
Presolved: 703 rows, 282 columns, 2034 nonzeros
Presolved model has 10 bilinear constraint(s)

Solving non-convex MIQCP to global optimality

Variable types: 242 continuous, 40 integer (39 binary)

Root relaxation: objective 9.830796e-01, 293 iterations, 0.00 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    0.98308    0   11    0.68041    0.98308  44.5%     -    0s
     0     0    0.96732    0   20    0.68041    0.96732  42.2%     -    0s
     0     0    0.96538    0   20    0.68041    0.96538  41.9%     -    0s
     0     0    0.96441    0   20    0.68041    0.96441  41.7%     -    0s
     0     0    0.95699    0   20    0.68041    0.95699  40.7%     -    0s
     0     0    0.93721    0   20    0.68041    0.93721  37.7%     -    0s
     0     0    0.93200    0   20    0.68041    0.93200  37.0%     -    0s
     0     0    0.91344    0   20    0.68041    0.91344  34.2%     -    0s
     0     0    0.91157    0   20    0.68041    0.91157  34.0%     -    0s
     0     0    0.91066    0   20    0.68041    0.91066  33.8%     -    0s
     0     0    0.90565    0   20    0.68041    0.90565  33.1%     -    0s
     0     0    0.87212    0   18    0.68041    0.87212  28.2%     -    0s
     0     0    0.87018    0   18    0.68041    0.87018  27.9%     -    0s
     0     0    0.85548    0   18    0.68041    0.85548  25.7%     -    0s
     0     0    0.84571    0   18    0.68041    0.84571  24.3%     -    0s
     0     0    0.84136    0   19    0.68041    0.84136  23.7%     -    0s
     0     0    0.82573    0   18    0.68041    0.82573  21.4%     -    0s
     0     0    0.81849    0   17    0.68041    0.81849  20.3%     -    0s
     0     0    0.81785    0   17    0.68041    0.81785  20.2%     -    0s
     0     0    0.81439    0   17    0.68041    0.81439  19.7%     -    0s
     0     0    0.81419    0   16    0.68041    0.81419  19.7%     -    0s
     0     0    0.80723    0   17    0.68041    0.80723  18.6%     -    0s
     0     0    0.80723    0   17    0.68041    0.80723  18.6%     -    0s
     0     0    0.79655    0   17    0.68041    0.79655  17.1%     -    0s
     0     0    0.78659    0   19    0.68041    0.78659  15.6%     -    0s
     0     0    0.78659    0   19    0.68041    0.78659  15.6%     -    0s
     0     2    0.78659    0   19    0.68041    0.78659  15.6%     -    0s

Cutting planes:
  Gomory: 5
  MIR: 52
  Flow cover: 95
  RLT: 42
  Relax-and-lift: 6
  BQP: 61

Explored 2133 nodes (13760 simplex iterations) in 0.28 seconds (0.40 work units)
Thread count was 24 (of 24 available processors)

Solution count 5: 0.680407 0.678559 0.672517 ... 0.628188

Optimal solution found (tolerance 1.00e-02)
Best objective 6.804072772339e-01, best bound 6.847415702238e-01, gap 0.6370%


=====================================
=====================================
Set parameter LogToConsole to value 1
Set parameter TimeLimit to value 90
Set parameter MIPGap to value 0.1
Set parameter NonConvex to value 2
Gurobi Optimizer version 13.0.1 build v13.0.1rc0 (linux64 - "Ubuntu 24.04.4 LTS")

CPU model: AMD Ryzen 9 7900 12-Core Processor, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 12 physical cores, 24 logical processors, using up to 24 threads

Non-default parameters:
TimeLimit  90
MIPGap  0.1
NonConvex  2

Optimize a model with 21 rows, 102 columns and 94 nonzeros (Max)
Model fingerprint: 0x1227911a
Model has 10 linear objective coefficients
Model has 30 quadratic constraints
Model has 114 simple general constraints
  10 MAX, 20 AND, 84 INDICATOR
Variable types: 60 continuous, 42 integer (42 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [5e-01, 1e+01]
  Objective range  [1e-01, 1e-01]
  Bounds range     [1e+00, 1e+01]
  RHS range        [1e+00, 1e+00]
  GenCon rhs range [1e+00, 2e+00]
  GenCon coe range [1e+00, 1e+00]

Using branch priorities.
User MIP start produced solution with objective 0.628188 (0.00s)
User MIP start produced solution with objective 0.658185 (0.00s)
User MIP start produced solution with objective 0.672517 (0.00s)
User MIP start produced solution with objective 0.678559 (0.01s)
User MIP start produced solution with objective 0.680407 (0.01s)
Loaded user MIP start with objective 0.680407

Presolve added 136 rows and 17 columns
Presolve time: 0.00s
Presolved: 703 rows, 282 columns, 2034 nonzeros
Presolved model has 10 bilinear constraint(s)

Solving non-convex MIQCP to global optimality

Variable types: 242 continuous, 40 integer (39 binary)

Root relaxation: objective 9.830796e-01, 293 iterations, 0.00 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    0.98308    0   11    0.68041    0.98308  44.5%     -    0s
     0     0    0.96732    0   20    0.68041    0.96732  42.2%     -    0s
     0     0    0.96538    0   20    0.68041    0.96538  41.9%     -    0s
     0     0    0.96441    0   20    0.68041    0.96441  41.7%     -    0s
     0     0    0.95699    0   20    0.68041    0.95699  40.7%     -    0s
     0     0    0.93721    0   20    0.68041    0.93721  37.7%     -    0s
     0     0    0.93200    0   20    0.68041    0.93200  37.0%     -    0s
     0     0    0.91344    0   20    0.68041    0.91344  34.2%     -    0s
     0     0    0.91157    0   20    0.68041    0.91157  34.0%     -    0s
     0     0    0.91066    0   20    0.68041    0.91066  33.8%     -    0s
     0     0    0.90565    0   20    0.68041    0.90565  33.1%     -    0s
     0     0    0.87212    0   18    0.68041    0.87212  28.2%     -    0s
     0     0    0.87018    0   18    0.68041    0.87018  27.9%     -    0s
     0     0    0.85548    0   18    0.68041    0.85548  25.7%     -    0s
     0     0    0.84571    0   18    0.68041    0.84571  24.3%     -    0s
     0     0    0.84136    0   19    0.68041    0.84136  23.7%     -    0s
     0     0    0.82573    0   18    0.68041    0.82573  21.4%     -    0s
     0     0    0.81849    0   17    0.68041    0.81849  20.3%     -    0s
     0     0    0.81785    0   17    0.68041    0.81785  20.2%     -    0s
     0     0    0.81439    0   17    0.68041    0.81439  19.7%     -    0s
     0     0    0.81419    0   16    0.68041    0.81419  19.7%     -    0s
     0     0    0.80723    0   17    0.68041    0.80723  18.6%     -    0s
     0     0    0.80723    0   17    0.68041    0.80723  18.6%     -    0s
     0     0    0.79655    0   17    0.68041    0.79655  17.1%     -    0s
     0     0    0.78659    0   19    0.68041    0.78659  15.6%     -    0s
     0     0    0.78659    0   19    0.68041    0.78659  15.6%     -    0s
     0     2    0.78659    0   19    0.68041    0.78659  15.6%     -    0s

Cutting planes:
  Gomory: 5
  MIR: 52
  Flow cover: 95
  RLT: 42
  Relax-and-lift: 6
  BQP: 61

Explored 193 nodes (9622 simplex iterations) in 0.23 seconds (0.31 work units)
Thread count was 24 (of 24 available processors)

Solution count 5: 0.680407 0.678559 0.672517 ... 0.628188

Optimal solution found (tolerance 1.00e-01)
Best objective 6.804072772339e-01, best bound 7.434996924082e-01, gap 9.2727%


=====================================
=====================================
Set parameter LogToConsole to value 1
Set parameter TimeLimit to value 90
Set parameter MIPGap to value 0.25
Set parameter NonConvex to value 2
Gurobi Optimizer version 13.0.1 build v13.0.1rc0 (linux64 - "Ubuntu 24.04.4 LTS")

CPU model: AMD Ryzen 9 7900 12-Core Processor, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 12 physical cores, 24 logical processors, using up to 24 threads

Non-default parameters:
TimeLimit  90
MIPGap  0.25
NonConvex  2

Optimize a model with 21 rows, 102 columns and 94 nonzeros (Max)
Model fingerprint: 0x1227911a
Model has 10 linear objective coefficients
Model has 30 quadratic constraints
Model has 114 simple general constraints
  10 MAX, 20 AND, 84 INDICATOR
Variable types: 60 continuous, 42 integer (42 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [5e-01, 1e+01]
  Objective range  [1e-01, 1e-01]
  Bounds range     [1e+00, 1e+01]
  RHS range        [1e+00, 1e+00]
  GenCon rhs range [1e+00, 2e+00]
  GenCon coe range [1e+00, 1e+00]

Using branch priorities.
User MIP start produced solution with objective 0.628188 (0.00s)
User MIP start produced solution with objective 0.658185 (0.00s)
User MIP start produced solution with objective 0.672517 (0.00s)
User MIP start produced solution with objective 0.678559 (0.01s)
User MIP start produced solution with objective 0.680407 (0.01s)
Loaded user MIP start with objective 0.680407

Presolve added 136 rows and 17 columns
Presolve time: 0.00s
Presolved: 703 rows, 282 columns, 2034 nonzeros
Presolved model has 10 bilinear constraint(s)

Solving non-convex MIQCP to global optimality

Variable types: 242 continuous, 40 integer (39 binary)

Root relaxation: objective 9.830796e-01, 293 iterations, 0.00 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    0.98308    0   11    0.68041    0.98308  44.5%     -    0s
     0     0    0.96732    0   20    0.68041    0.96732  42.2%     -    0s
     0     0    0.96538    0   20    0.68041    0.96538  41.9%     -    0s
     0     0    0.96441    0   20    0.68041    0.96441  41.7%     -    0s
     0     0    0.95699    0   20    0.68041    0.95699  40.7%     -    0s
     0     0    0.93721    0   20    0.68041    0.93721  37.7%     -    0s
     0     0    0.93200    0   20    0.68041    0.93200  37.0%     -    0s
     0     0    0.91344    0   20    0.68041    0.91344  34.2%     -    0s
     0     0    0.91157    0   20    0.68041    0.91157  34.0%     -    0s
     0     0    0.91066    0   20    0.68041    0.91066  33.8%     -    0s
     0     0    0.90565    0   20    0.68041    0.90565  33.1%     -    0s
     0     0    0.87212    0   18    0.68041    0.87212  28.2%     -    0s
     0     0    0.87018    0   18    0.68041    0.87018  27.9%     -    0s
     0     0    0.85548    0   18    0.68041    0.85548  25.7%     -    0s
     0     0    0.84571    0   18    0.68041    0.84571  24.3%     -    0s

Cutting planes:
  Gomory: 3
  MIR: 18
  Flow cover: 58
  RLT: 10
  BQP: 14
  PSD: 1

Explored 1 nodes (1135 simplex iterations) in 0.10 seconds (0.12 work units)
Thread count was 24 (of 24 available processors)

Solution count 5: 0.680407 0.678559 0.672517 ... 0.628188

Optimal solution found (tolerance 2.50e-01)
Best objective 6.804072772339e-01, best bound 8.457103065361e-01, gap 24.2947%


=====================================

## Check for errors in the data

You always want to check if the results you got are actually feasible. Errors
easily happen and are not always visible on the plots. Thus, you want to do some
basic checks to detect errors early on. For example, you could accidentally have
swapped lower and upper bounds in the data generation process. Depending on your
plots, this may not be visible, and you may end up comparing the wrong data and
draw the wrong conclusions. Or, you could have accidentally swapped runtime and
objective values, which could look reasonable in the data as the runtime and the
objective often increase with the instance size.

A very basic check is to check if the best lower and upper bounds do not
contradict each other. Many errors will be caught by this check. However, you
often need some tolerance to account for numerical errors.

In [9]:
assert (t.dropna()["opt_gap"] >= -0.0001).all(), "Optimality gap is negative!"

In [12]:
from IPython.display import display

# Always make sure that your results are not trivially wrong
#  - e.g. upper bound is lower than objective
min_ub = t.groupby(["instance_name"])[ResultKey.UPPER_BOUND].min()
max_obj = t.groupby(["instance_name"])[ResultKey.OBJECTIVE].max()
print(min_ub)
print(max_obj)
eps = 0.0001  # some tolerance is needed when working with floats.
bad_instances = min_ub[abs(min_ub - max_obj) > eps * min_ub].index.to_list()

display(t[t["instance_name"].isin(bad_instances)])
assert len(bad_instances) == 0, "Bad instances detected: {}".format(bad_instances)

instance_name
blob_N10_K2_D1_seed0    0.558582
blob_N10_K2_D1_seed1    0.680889
blob_N10_K2_D1_seed2    0.746616
blob_N10_K2_D2_seed0    0.553847
blob_N10_K2_D2_seed1    0.857719
                          ...
blob_N8_K4_D2_seed1     0.597410
blob_N8_K4_D2_seed2     0.629531
blob_N8_K4_D3_seed0     0.590646
blob_N8_K4_D3_seed1     0.773196
blob_N8_K4_D3_seed2     0.673238
Name: upper_bound, Length: 108, dtype: float64
instance_name
blob_N10_K2_D1_seed0    0.558582
blob_N10_K2_D1_seed1    0.680407
blob_N10_K2_D1_seed2    0.746574
blob_N10_K2_D2_seed0    0.553816
blob_N10_K2_D2_seed1    0.857261
                          ...
blob_N8_K4_D2_seed1     0.597390
blob_N8_K4_D2_seed2     0.629226
blob_N8_K4_D3_seed0     0.590606
blob_N8_K4_D3_seed1     0.773195
blob_N8_K4_D3_seed2     0.672723
Name: objective, Length: 108, dtype: float64

,instance_name,num_points,num_clusters,num_dimensions,time_limit,runtime,strategy,opt_tol,objective,upper_bound,opt_gap
0,blob_N11_K2_D1_seed1,11,2,1,90,0.386309,GurobiSilhouetteSolver,0.001,0.713968,0.714474,0.000708
1,blob_N11_K2_D1_seed1,11,2,1,90,0.310472,GurobiSilhouetteSolver,0.010,0.713968,0.718373,0.006131
2,blob_N11_K2_D1_seed1,11,2,1,90,0.239164,GurobiSilhouetteSolver,0.100,0.713968,0.781892,0.086871
3,blob_N11_K2_D1_seed1,11,2,1,90,0.107098,GurobiSilhouetteSolver,0.250,0.713968,0.885078,0.193327
4,blob_N8_K2_D1_seed2,8,2,1,90,0.633261,GurobiSilhouetteSolver,0.001,0.817650,0.818405,0.000923
...,...,...,...,...,...,...,...,...,...,...,...
433,blob_N5_K3_D3_seed0,5,3,3,90,0.032977,GurobiSilhouetteSolver,0.250,0.473460,0.582076,0.186601
446,blob_N10_K2_D1_seed1,10,2,1,90,0.312366,GurobiSilhouetteSolver,0.001,0.680407,0.680889,0.000708
447,blob_N10_K2_D1_seed1,10,2,1,90,0.288597,GurobiSilhouetteSolver,0.010,0.680407,0.684742,0.006330
448,blob_N10_K2_D1_seed1,10,2,1,90,0.230771,GurobiSilhouetteSolver,0.100,0.680407,0.743500,0.084859
449,blob_N10_K2_D1_seed1,10,2,1,90,0.106643,GurobiSilhouetteSolver,0.250,0.680407,0.845710,0.195461

AssertionError: Bad instances detected: ['blob_N10_K2_D1_seed1', 'blob_N10_K2_D2_seed1', 'blob_N10_K2_D2_seed2', 'blob_N10_K3_D1_seed1', 'blob_N10_K3_D1_seed2', 'blob_N10_K3_D2_seed2', 'blob_N10_K3_D3_seed1', 'blob_N10_K3_D3_seed2', 'blob_N10_K4_D1_seed2', 'blob_N11_K2_D1_seed1', 'blob_N11_K2_D2_seed1', 'blob_N11_K2_D2_seed2', 'blob_N11_K3_D1_seed0', 'blob_N11_K3_D1_seed1', 'blob_N11_K3_D1_seed2', 'blob_N11_K3_D2_seed0', 'blob_N11_K3_D2_seed2', 'blob_N11_K3_D3_seed1', 'blob_N11_K3_D3_seed2', 'blob_N11_K4_D1_seed0', 'blob_N5_K2_D1_seed1', 'blob_N5_K2_D2_seed0', 'blob_N5_K2_D2_seed1', 'blob_N5_K2_D3_seed1', 'blob_N5_K2_D3_seed2', 'blob_N5_K3_D1_seed1', 'blob_N5_K3_D2_seed0', 'blob_N5_K3_D2_seed1', 'blob_N5_K3_D3_seed0', 'blob_N5_K4_D3_seed1', 'blob_N8_K2_D1_seed1', 'blob_N8_K2_D1_seed2', 'blob_N8_K2_D2_seed0', 'blob_N8_K2_D2_seed1', 'blob_N8_K2_D3_seed2', 'blob_N8_K3_D1_seed1', 'blob_N8_K3_D2_seed0', 'blob_N8_K3_D2_seed1', 'blob_N8_K3_D2_seed2', 'blob_N8_K3_D3_seed1', 'blob_N8_K4_D2_seed0', 'blob_N8_K4_D2_seed2', 'blob_N8_K4_D3_seed2']